computation-engine:
   messaging:
      exchange: computations
      requestQueue: requests
      payloadQueue: payloads
      requestRoutingKey: requests
      payloadRoutingKey: payloads
   repository:
      host: ce_cassandra
      port: 9042
      keyspace: computations
spring:
   rabbitmq:
      username: guest
      password: guest
      host: ce_rabbit
      port: 5672