computation-engine:
   messaging:
      exchange: computations
      requestQueue: requests
      payloadQueue: payloads
      requestRoutingKey: requests
      payloadsRoutingKey: payloads
   repository:
      host: 127.0.0.1
      port: 9042
      keyspace: computations